### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by olimortimer** [XeroAPI/xoauth#2]
Installed xoauth on Mac macOS Catalina 10.15.3 but when I attempt to connect I receive a `TLS handshake timeout`.  If I `curl https://identity.xero.com/.well-known/openid-configuration` it can read the site / file fine, but not during connect;

```
Requesting OIDC metadata from https://identity.xero.com/.well-known/openid-configuration
panic: Get https://identity.xero.com/.well-known/openid-configuration: net/http: TLS handshake timeout

goroutine 1 [running]:
github.com/xero-github/xoauth/pkg/connect.Authorise(0x7ffeefbffc67, 0x7, 0xc0000c1d00, 0x1f90)
	/home/runner/work/xoauth/xoauth/pkg/connect/connect.go:40 +0x577
github.com/xero-github/xoauth/cmd.init.0.func3(0xc0000a3680, 0xc00005d250, 0x1, 0x1)
	/home/runner/work/xoauth/xoauth/cmd/root.go:71 +0x5d
github.com/spf13/cobra.(*Command).execute(0xc0000a3680, 0xc00005d210, 0x1, 0x1, 0xc0000a3680, 0xc00005d210)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1863660, 0x0, 0x1421c60, 0xc00007e058)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/xero-github/xoauth/cmd.Execute(...)
	/home/runner/work/xoauth/xoauth/cmd/root.go:196
main.main()
	/home/runner/work/xoauth/xoauth/xoauth.go:13 +0x47
```

**Comment by JoshBarr** [comment]
Hey @olimortimer, I'm looking into this issue. Are you behind a firewall, VPN or any other kind of proxy? I'm thinking we may need to update xoauth to respect the system proxy, if that turns out to be the issue!

**Comment by olimortimer** [comment]
@JoshBarr that was my first thought, but unfortunately not.  I did actually try it behind a VPN, but it made no difference either.  Also tried with 2 other ISPs, but still the same error.

**Comment by dr-ummond** [comment]
@olimortimer and @JoshBarr did this issue get resolved, I am experiencing the same issue.
