### ISSUE TITLE
Broken on Windows

### ISSUE THREAD

**Issue by silenuz** [XeroAPI/xoauth#20]
While version 1.0 didn't allow saving to the  local keychain in windows, which appears to be fixed in 1.1, however while it's nice that they are actually saved now it is impossible to retrieve them.

a call to xoauth token client results in:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7a7b6d]

goroutine 1 [running]:
github.com/XeroAPI/xoauth/pkg/keyring.WindowsKeyRingService.GetTokens(0xc00001e0b0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/xoauth/xoauth/pkg/keyring/windowsKeyring.go:63 +0x1dd
github.com/XeroAPI/xoauth/pkg/db.(*CredentialStore).GetTokens(0xc0000411f0, 0xc00001e0b0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/xoauth/xoauth/pkg/db/db.go:283 +0xa7
github.com/XeroAPI/xoauth/pkg/tokens.ShowTokens(0xc0000411f0, 0xc00001e0b0, 0x4, 0x800000)
        /home/runner/work/xoauth/xoauth/pkg/tokens/tokens.go:22 +0xee
github.com/XeroAPI/xoauth/cmd.init.0.func11(0xc0000f02c0, 0xc0000411d0, 0x1, 0x1)
        /home/runner/work/xoauth/xoauth/cmd/root.go:189 +0x133
github.com/spf13/cobra.(*Command).execute(0xc0000f02c0, 0xc0000411a0, 0x1, 0x1, 0xc0000f02c0, 0xc0000411a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0xcaf140, 0x0, 0x850660, 0xc000024118)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/XeroAPI/xoauth/cmd.Execute(...)
        /home/runner/work/xoauth/xoauth/cmd/root.go:254
main.main()
        /home/runner/work/xoauth/xoauth/xoauth.go:13 +0x4e
```

Which in turns breaks the --refresh option as well.  It would be nice to have a working version on windows.

**Comment by chrisgleaves** [comment]
I have exactly the same issue (running W10 20H2)

**Comment by AjitSharmaTofrum** [comment]
@silenuz were you are to resolve the issue. If yes, can you please share the steps.

**Comment by silenuz** [comment]
Line 63 in the windowskeyring.go file is where it breaks.

On line 63:

```
// Since these params are optional, ignore not found errors
	if err.Error() != keyring.ErrNotFound.Error() {
		return result, err
	}

```
At this point err is nil. So maybe it should be:

```
// Since these params are optional, ignore not found errors
	if err != nil && err.Error() != keyring.ErrNotFound.Error() {
		return result, err
	}

```
The code is in Go, so it's easy enough to fix and recompile.  As this project seems abandoned if there is interest I may consider forking this project and fixing it.

**Comment by manishchhettri** [comment]
This was a real pain to work around, works fine on mac fails in windows. Worked past it by doing the setup and the connect via powershell command line invoked through a java program. The refresh code was done in java using com.google.api.client.auth.oauth2 APIs to refresh the token.

**Comment by dm-efi** [comment]
I suspect the bug occurs when the key storage requirements doesn't need a second 2 windows key ring because the number of scopes is small enough to fit into one key ring. When it tries to read back the second key ring it crashes. I'd rather Xero fix this and create another executable rather than download and install the go environment myself.
